// <auto-generated />
namespace Surat.Document.Base.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V2212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V2212));
        
        string IMigrationMetadata.Id
        {
            get { return "201512221431559_V22.12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
