// <auto-generated />
namespace Surat.Base.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V1412 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V1412));
        
        string IMigrationMetadata.Id
        {
            get { return "201512141356331_V14.12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
